/*file descriptions overview:
    package.json => project configurations stored here
    index.js => my server code
    node modules folder => where all the node packages are stored
    package-lock.json => auto generated by npm init command; keeps track of the dependencies and versions of my packages - don't need to touch this file
    index.html => the file thatI want to see when I make a connection with our server

    What do I want my server to do?
        [] serve+host my web page, index.html
        [] save and retrieve information from a database and pass it to the client
        [] API authentications

    General notes:
    - Using express to host static files (node server displaying the files that are in the "public" folder of this project)


*/


//importing express package into the project
const express = require('express');

//importing NeDB packages
const Datastore = require('nedb');

//creating a web app, by using express, by calling the express function
const app = express();

//creating a server locally on my laptop and listening for commands on port specified 
app.listen(3000, ()=> console.log('listening at port 3000'));

//public is a directory name, anything that is put in here can be seen and accessed by anyone from the url localhost:3000
app.use(express.static('public'));

//enabling our server to read incoming data that is in JSON format, limiting the size of data to 1MB to prevent someone from flooding our server
app.use(express.json({limit: '1mb'}));

//database will sit in a local file on my computer for now because that's where i'm currently running the server
//calling our file 'database.db' - this is where we're going to save data recieved from the client
const database = new Datastore('database.db');



//will load the pre-existing file from when the DB last ran.
//if there is none, it will create that file
database.loadDatabase();

//defining the route of the post request
//request variable - holds everything that is contained within that request (sent my client)
//response variable - a variable we can use to send any data back to the client
// '/api' is what our endpoint is called - we will be recieving data from the client at this endpoint
app.post('/api', (request, response) => {
    console.log('I got a request!');
    console.log('Sending response back:');   
    //console.log(request.body);
    const data = request.body;

    //creating timestamp for each submission into the DB
    const timestamp = Date.now(); 
    data.timestamp = timestamp;

    //database.push(data); -> don't need to push new objects into the array now that we have set up our DB 
    //inserting info into DB -> into the NeDB Datastore (into our database.db file)
    database.insert(data);
    
    //console.log(database);

    //being a polite server and sending back a response to the request that was received
    response.json({
        status: "success",
        timestamp: timestamp,
        latitude: data.latitude,
        longitude: data.longitude,
        description: data.description
    });

});

// app.post('/photo', (request, response) => {
//     console.log('I got a request!');
//     console.log('Sending response back:');   
//     //console.log(request.body);
//     const data = request.body;

//     //creating timestamp for each submission into the DB
//     const timestamp = Date.now(); 
//     data.timestamp = timestamp;

//     //database.push(data); -> don't need to push new objects into the array now that we have set up our DB 
//     //inserting info into DB -> into the NeDB Datastore (into our database.db file)
//     database.insert(data);
    
//     //console.log(database);

//     //being a polite server and sending back a response to the request that was received
//     response.json({
//         status: "success",
//         timestamp: timestamp,
        
//     });

// });